from .agregarRegistrosView import CrearRegistro
from .CRUDUbicacionView import UnRegistroidUbicacion, MostarTodasUbicaciones, CrearUbicacion, ActualizarUbicacion
from .visualizarRegistros import MostarRegistros