# Generated by Django 3.2.8 on 2021-10-28 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_caso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_notificacion', models.DateField()),
                ('fecha_reporte', models.DateField()),
                ('fecha_sintomas', models.DateField()),
                ('fecha_diagnostico_lab', models.DateField()),
                ('edad', models.IntegerField()),
                ('unidad_de_medida_edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=5)),
                ('grupo_etnico', models.CharField(max_length=30)),
                ('pertenencia_etnica', models.IntegerField()),
                ('fecha_recuperacion', models.DateField()),
                ('tipo_recuperacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('codigoDivipolaMunicipio', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_iso_pais', models.IntegerField(default=0)),
                ('nombre_pais', models.CharField(max_length=30, verbose_name='Nombre_del_pais')),
                ('codigo_divipola_departamento', models.IntegerField(default=0)),
                ('nombre_departamento', models.CharField(max_length=30, verbose_name='Nombre_del_departamento')),
                ('nombre_municipio', models.CharField(max_length=30, verbose_name='Nombre_del_municipio')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('is_staff', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seguimiento_de_cambios',
            fields=[
                ('id_evolucion', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion_caso', models.CharField(max_length=30, verbose_name='Ubicacion_caso')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('tipo_contagio', models.CharField(max_length=20, verbose_name='Tipo_de_contagio')),
                ('recuperado', models.CharField(max_length=20, verbose_name='Recuperado')),
                ('fecha_muerte', models.DateField(null=True)),
                ('id_caso_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppCovid19.registro')),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='codigo_divipola_municipio_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCovid19.ubicacion'),
        ),
    ]
