# Generated by Django 3.2.7 on 2021-10-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion_geografica',
            fields=[
                ('codigo_divipola_municipio', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_iso_pais', models.IntegerField(default=0)),
                ('nombre_pais', models.CharField(max_length=30, verbose_name='Nombre_del_pais')),
                ('codigo_divipola_departamento', models.IntegerField(default=0)),
                ('nombre_departamento', models.CharField(max_length=30, verbose_name='Nombre_del_departamento')),
                ('nombre_municipio', models.CharField(max_length=30, verbose_name='Nombre_del_municipio')),
            ],
        ),
    ]
