# Generated by Django 3.2.8 on 2021-10-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCovid19', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento_de_cambios',
            name='id_evolucion',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
