# Generated by Django 3.2.7 on 2021-10-08 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCovid19', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_caso', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_notificacion', models.DateTimeField()),
                ('fecha_reporte', models.DateTimeField()),
                ('fecha_sintomas', models.DateTimeField()),
                ('fecha_diagnostico_lab', models.DateTimeField()),
                ('edad', models.IntegerField()),
                ('unidad_de_medida_edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=5, verbose_name='Sexo')),
                ('grupo_etnico', models.CharField(max_length=30, verbose_name='Grupo_etnico')),
                ('pertenencia_etnica', models.CharField(max_length=30, verbose_name='Pertenencia_etnica')),
                ('fecha_recuperacion', models.DateField()),
                ('tipo_recuperacion', models.CharField(max_length=20, verbose_name='Tipo_de_recuperacion')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('codigoDivipolaMunicipio', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_iso_pais', models.IntegerField(default=0)),
                ('nombre_pais', models.CharField(max_length=30, verbose_name='Nombre_del_pais')),
                ('codigo_divipola_departamento', models.IntegerField(default=0)),
                ('nombre_departamento', models.CharField(max_length=30, verbose_name='Nombre_del_departamento')),
                ('nombre_municipio', models.CharField(max_length=30, verbose_name='Nombre_del_municipio')),
            ],
        ),
        migrations.DeleteModel(
            name='Ubicacion_geografica',
        ),
        migrations.AddField(
            model_name='registro',
            name='codigo_divipola_municipio_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCovid19.ubicacion'),
        ),
    ]
