# Generated by Django 3.2.7 on 2021-10-08 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCovid19', '0002_auto_20211008_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento_de_cambios',
            fields=[
                ('id_evolucion', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion_caso', models.CharField(max_length=30, verbose_name='Ubicacion_caso')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('tipo_contagio', models.CharField(max_length=20, verbose_name='Tipo_de_contagio')),
                ('recuperado', models.CharField(max_length=20, verbose_name='Recuperado')),
                ('fecha_muerte', models.DateTimeField(auto_now_add=True)),
                ('id_del_caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCovid19.registro')),
            ],
        ),
    ]
