# Generated by Django 3.2.8 on 2021-10-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCovid19', '0003_seguimiento_de_cambios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguimiento_de_cambios',
            old_name='id_del_caso',
            new_name='id_del_caso_fk',
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_diagnostico_lab',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_notificacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_reporte',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_sintomas',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='seguimiento_de_cambios',
            name='fecha_muerte',
            field=models.DateField(),
        ),
    ]
