# Generated by Django 3.2.7 on 2021-10-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCovid19', '0006_alter_registro_id_evolucion_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='grupo_etnico',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='registro',
            name='pertenencia_etnica',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='sexo',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo_recuperacion',
            field=models.CharField(max_length=20),
        ),
    ]
