# Generated by Django 3.2.7 on 2021-10-15 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCovid19', '0008_alter_seguimiento_de_cambios_id_evolucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='id_evolucion_fk',
        ),
        migrations.AddField(
            model_name='seguimiento_de_cambios',
            name='id_caso_fk',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCovid19.registro'),
        ),
        migrations.AlterField(
            model_name='seguimiento_de_cambios',
            name='id_evolucion',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
