# Generated by Django 3.2.7 on 2021-10-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCovid19', '0010_alter_registro_id_caso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento_de_cambios',
            name='id_caso_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppCovid19.registro'),
        ),
    ]
