# Generated by Django 3.2.8 on 2021-10-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCovid19', '0011_alter_seguimiento_de_cambios_id_caso_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='id_caso',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seguimiento_de_cambios',
            name='id_evolucion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
